// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ServiceRegist.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MessageType int32

const (
	MessageType_Request  MessageType = 0
	MessageType_Response MessageType = 1
	MessageType_Notify   MessageType = 2
)

var MessageType_name = map[int32]string{
	0: "Request",
	1: "Response",
	2: "Notify",
}

var MessageType_value = map[string]int32{
	"Request":  0,
	"Response": 1,
	"Notify":   2,
}

func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}

func (MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f5f0fbfcd914aaea, []int{0}
}

type RegisterType int32

const (
	RegisterType_Register   RegisterType = 0
	RegisterType_UnRegister RegisterType = 1
)

var RegisterType_name = map[int32]string{
	0: "Register",
	1: "UnRegister",
}

var RegisterType_value = map[string]int32{
	"Register":   0,
	"UnRegister": 1,
}

func (x RegisterType) String() string {
	return proto.EnumName(RegisterType_name, int32(x))
}

func (RegisterType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f5f0fbfcd914aaea, []int{1}
}

type RegisterServiceRequest struct {
	ClientName           string       `protobuf:"bytes,1,opt,name=clientName,proto3" json:"clientName,omitempty"`
	RegType              RegisterType `protobuf:"varint,2,opt,name=regType,proto3,enum=protobuf.RegisterType" json:"regType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RegisterServiceRequest) Reset()         { *m = RegisterServiceRequest{} }
func (m *RegisterServiceRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterServiceRequest) ProtoMessage()    {}
func (*RegisterServiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5f0fbfcd914aaea, []int{0}
}

func (m *RegisterServiceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterServiceRequest.Unmarshal(m, b)
}
func (m *RegisterServiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterServiceRequest.Marshal(b, m, deterministic)
}
func (m *RegisterServiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterServiceRequest.Merge(m, src)
}
func (m *RegisterServiceRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterServiceRequest.Size(m)
}
func (m *RegisterServiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterServiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterServiceRequest proto.InternalMessageInfo

func (m *RegisterServiceRequest) GetClientName() string {
	if m != nil {
		return m.ClientName
	}
	return ""
}

func (m *RegisterServiceRequest) GetRegType() RegisterType {
	if m != nil {
		return m.RegType
	}
	return RegisterType_Register
}

type RegisterServiceResponse struct {
	Status               int32       `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	MsgType              MessageType `protobuf:"varint,2,opt,name=msgType,proto3,enum=protobuf.MessageType" json:"msgType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *RegisterServiceResponse) Reset()         { *m = RegisterServiceResponse{} }
func (m *RegisterServiceResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterServiceResponse) ProtoMessage()    {}
func (*RegisterServiceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5f0fbfcd914aaea, []int{1}
}

func (m *RegisterServiceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterServiceResponse.Unmarshal(m, b)
}
func (m *RegisterServiceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterServiceResponse.Marshal(b, m, deterministic)
}
func (m *RegisterServiceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterServiceResponse.Merge(m, src)
}
func (m *RegisterServiceResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterServiceResponse.Size(m)
}
func (m *RegisterServiceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterServiceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterServiceResponse proto.InternalMessageInfo

func (m *RegisterServiceResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *RegisterServiceResponse) GetMsgType() MessageType {
	if m != nil {
		return m.MsgType
	}
	return MessageType_Request
}

func init() {
	proto.RegisterEnum("protobuf.MessageType", MessageType_name, MessageType_value)
	proto.RegisterEnum("protobuf.RegisterType", RegisterType_name, RegisterType_value)
	proto.RegisterType((*RegisterServiceRequest)(nil), "protobuf.RegisterServiceRequest")
	proto.RegisterType((*RegisterServiceResponse)(nil), "protobuf.RegisterServiceResponse")
}

func init() { proto.RegisterFile("ServiceRegist.proto", fileDescriptor_f5f0fbfcd914aaea) }

var fileDescriptor_f5f0fbfcd914aaea = []byte{
	// 225 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x8f, 0xd1, 0x4a, 0xc3, 0x40,
	0x10, 0x45, 0xbb, 0x05, 0x93, 0x7a, 0x5b, 0x4a, 0x18, 0x31, 0xf6, 0x49, 0x4a, 0x9f, 0x4a, 0x91,
	0x28, 0xea, 0x6f, 0xd8, 0x87, 0xa8, 0x1f, 0x90, 0x94, 0x69, 0x88, 0xd8, 0x6c, 0xdc, 0xd9, 0x08,
	0xfd, 0x7b, 0x31, 0x9b, 0x8d, 0x0b, 0x3e, 0x2d, 0x77, 0xe6, 0x30, 0xe7, 0x2e, 0xae, 0x5e, 0xd9,
	0x7c, 0xd7, 0x07, 0xce, 0xb9, 0xaa, 0xc5, 0x66, 0xad, 0xd1, 0x56, 0xd3, 0xac, 0x7f, 0xca, 0xee,
	0xb8, 0xf9, 0x40, 0xea, 0x36, 0x6c, 0x46, 0xf0, 0xab, 0x63, 0xb1, 0x74, 0x0b, 0x1c, 0x3e, 0x6b,
	0x6e, 0xec, 0xbe, 0x38, 0xf1, 0x4a, 0xad, 0xd5, 0xf6, 0x32, 0x0f, 0x26, 0xf4, 0x80, 0xd8, 0x70,
	0xf5, 0x76, 0x6e, 0x79, 0x35, 0x5d, 0xab, 0xed, 0xf2, 0x31, 0xcd, 0xfc, 0xd5, 0xcc, 0x9f, 0xfc,
	0xdd, 0xe6, 0x1e, 0xdb, 0x94, 0xb8, 0xf9, 0xe7, 0x92, 0x56, 0x37, 0xc2, 0x94, 0x22, 0x12, 0x5b,
	0xd8, 0x4e, 0x7a, 0xd1, 0x45, 0x3e, 0x24, 0xba, 0x47, 0x7c, 0x92, 0x50, 0x72, 0xfd, 0x27, 0x79,
	0x61, 0x91, 0xa2, 0x62, 0xe7, 0x18, 0xa8, 0xdd, 0x33, 0xe6, 0xc1, 0x9c, 0xe6, 0x88, 0x87, 0xff,
	0x24, 0x13, 0x5a, 0x60, 0xe6, 0x85, 0x89, 0x22, 0x20, 0xda, 0x6b, 0x5b, 0x1f, 0xcf, 0xc9, 0x74,
	0x77, 0x87, 0x45, 0x58, 0xd9, 0x91, 0x2e, 0x27, 0x13, 0x5a, 0x02, 0xef, 0xcd, 0x98, 0x55, 0x19,
	0xf5, 0x15, 0x9e, 0x7e, 0x02, 0x00, 0x00, 0xff, 0xff, 0xd6, 0x03, 0xeb, 0xfc, 0x5b, 0x01, 0x00,
	0x00,
}
