// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ServiceProto.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SendMessageType int32

const (
	SendMessageType_RequestServer  SendMessageType = 0
	SendMessageType_ResponseServer SendMessageType = 1
	SendMessageType_NotifyServer   SendMessageType = 2
	SendMessageType_RequestClient  SendMessageType = 3
	SendMessageType_ResponseClient SendMessageType = 4
	SendMessageType_NotifyClient   SendMessageType = 5
)

var SendMessageType_name = map[int32]string{
	0: "RequestServer",
	1: "ResponseServer",
	2: "NotifyServer",
	3: "RequestClient",
	4: "ResponseClient",
	5: "NotifyClient",
}

var SendMessageType_value = map[string]int32{
	"RequestServer":  0,
	"ResponseServer": 1,
	"NotifyServer":   2,
	"RequestClient":  3,
	"ResponseClient": 4,
	"NotifyClient":   5,
}

func (x SendMessageType) String() string {
	return proto.EnumName(SendMessageType_name, int32(x))
}

func (SendMessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_af8ec4ef886c3416, []int{0}
}

type ProtoMessage struct {
	TargetClient         string          `protobuf:"bytes,1,opt,name=targetClient,proto3" json:"targetClient,omitempty"`
	MessageType          SendMessageType `protobuf:"varint,2,opt,name=messageType,proto3,enum=protobuf.SendMessageType" json:"messageType,omitempty"`
	FromClient           string          `protobuf:"bytes,3,opt,name=fromClient,proto3" json:"fromClient,omitempty"`
	MessageID            int32           `protobuf:"varint,4,opt,name=messageID,proto3" json:"messageID,omitempty"`
	Clients              []int64         `protobuf:"varint,5,rep,packed,name=clients,proto3" json:"clients,omitempty"`
	Sn                   int32           `protobuf:"varint,6,opt,name=sn,proto3" json:"sn,omitempty"`
	Body                 []byte          `protobuf:"bytes,7,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ProtoMessage) Reset()         { *m = ProtoMessage{} }
func (m *ProtoMessage) String() string { return proto.CompactTextString(m) }
func (*ProtoMessage) ProtoMessage()    {}
func (*ProtoMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_af8ec4ef886c3416, []int{0}
}

func (m *ProtoMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoMessage.Unmarshal(m, b)
}
func (m *ProtoMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoMessage.Marshal(b, m, deterministic)
}
func (m *ProtoMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoMessage.Merge(m, src)
}
func (m *ProtoMessage) XXX_Size() int {
	return xxx_messageInfo_ProtoMessage.Size(m)
}
func (m *ProtoMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoMessage proto.InternalMessageInfo

func (m *ProtoMessage) GetTargetClient() string {
	if m != nil {
		return m.TargetClient
	}
	return ""
}

func (m *ProtoMessage) GetMessageType() SendMessageType {
	if m != nil {
		return m.MessageType
	}
	return SendMessageType_RequestServer
}

func (m *ProtoMessage) GetFromClient() string {
	if m != nil {
		return m.FromClient
	}
	return ""
}

func (m *ProtoMessage) GetMessageID() int32 {
	if m != nil {
		return m.MessageID
	}
	return 0
}

func (m *ProtoMessage) GetClients() []int64 {
	if m != nil {
		return m.Clients
	}
	return nil
}

func (m *ProtoMessage) GetSn() int32 {
	if m != nil {
		return m.Sn
	}
	return 0
}

func (m *ProtoMessage) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func init() {
	proto.RegisterEnum("protobuf.SendMessageType", SendMessageType_name, SendMessageType_value)
	proto.RegisterType((*ProtoMessage)(nil), "protobuf.ProtoMessage")
}

func init() { proto.RegisterFile("ServiceProto.proto", fileDescriptor_af8ec4ef886c3416) }

var fileDescriptor_af8ec4ef886c3416 = []byte{
	// 264 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xbd, 0x4e, 0xf3, 0x30,
	0x14, 0x86, 0x3f, 0xe7, 0xa7, 0xfd, 0x7a, 0x08, 0x21, 0x9c, 0xc9, 0x48, 0x08, 0x45, 0x9d, 0x2c,
	0x86, 0x0c, 0x30, 0x32, 0xc2, 0xc2, 0x50, 0x84, 0x5c, 0x6e, 0xa0, 0x69, 0x4f, 0xaa, 0x48, 0xd4,
	0x0e, 0xb6, 0x8b, 0x94, 0x99, 0xcb, 0xe5, 0x26, 0x50, 0x5d, 0x57, 0x09, 0x2c, 0x89, 0xfd, 0xf8,
	0x79, 0x5f, 0x1d, 0x1d, 0xc0, 0x25, 0x99, 0xcf, 0x76, 0x4d, 0xaf, 0x46, 0x3b, 0x5d, 0x75, 0x87,
	0x2f, 0xfe, 0xf7, 0xbf, 0x7a, 0xdf, 0xcc, 0xbf, 0x19, 0x64, 0xfe, 0x65, 0x41, 0xd6, 0xae, 0xb6,
	0x84, 0x73, 0xc8, 0xdc, 0xca, 0x6c, 0xc9, 0x3d, 0xbe, 0xb7, 0xa4, 0x1c, 0x67, 0x25, 0x13, 0x33,
	0xf9, 0x8b, 0xe1, 0x03, 0x9c, 0xed, 0x8e, 0xfa, 0x5b, 0xdf, 0x11, 0x8f, 0x4a, 0x26, 0xf2, 0xbb,
	0xab, 0xea, 0x54, 0x5a, 0x2d, 0x49, 0x6d, 0x16, 0x83, 0x20, 0xc7, 0x36, 0xde, 0x00, 0x34, 0x46,
	0xef, 0x42, 0x7d, 0xec, 0xeb, 0x47, 0x04, 0xaf, 0x61, 0x16, 0xf4, 0xe7, 0x27, 0x9e, 0x94, 0x4c,
	0xa4, 0x72, 0x00, 0xc8, 0x61, 0xba, 0xf6, 0x9e, 0xe5, 0x69, 0x19, 0x8b, 0x58, 0x9e, 0xae, 0x98,
	0x43, 0x64, 0x15, 0x9f, 0xf8, 0x40, 0x64, 0x15, 0x22, 0x24, 0xb5, 0xde, 0xf4, 0x7c, 0x5a, 0x32,
	0x91, 0x49, 0x7f, 0xbe, 0xfd, 0x62, 0x70, 0xf1, 0x67, 0x38, 0xbc, 0x84, 0x73, 0x49, 0x1f, 0x7b,
	0xb2, 0xee, 0xb0, 0x28, 0x32, 0xc5, 0x3f, 0x44, 0xc8, 0x25, 0xd9, 0x4e, 0x2b, 0x4b, 0x81, 0x31,
	0x2c, 0x20, 0x7b, 0xd1, 0xae, 0x6d, 0xfa, 0x40, 0xa2, 0x51, 0xf0, 0x38, 0x79, 0x11, 0x8f, 0x83,
	0x81, 0x25, 0x43, 0x30, 0x90, 0xb4, 0x9e, 0xf8, 0x45, 0xdd, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff,
	0xb6, 0xfe, 0xd6, 0x64, 0x9a, 0x01, 0x00, 0x00,
}
